apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: emoji-svc
  namespace: emojivoto
spec:
  hosts:
  - emoji-svc
  http:
  - timeout: 3s
    retries:
      attempts: 3
      perTryTimeout: 1s
    route:
    - destination:
        host: emoji-svc
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: emoji-svc
  namespace: emojivoto
spec:
  host: emoji-svc
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
    outlierDetection:
      consecutiveErrors: 3
      interval: 30s
      baseEjectionTime: 30s